### PR TITLE
modelmerger: Introducing the extended specification language

### PR DESCRIPTION
**Pull request by krishnanm86**
Introducing the changes to the language specification as discussed previously. This includes the addition of concepts/editors/typesystem/constraints/behaviors related to the specification of child/property strategies for each concept. The goal is to lay the groundworks for future work involving the runtime changes and generator changes that follow.

### CODE REVIEW

**Comment by coolya** [comment]
I'm a bit confused here. There is still #142 where we discuss the spec and how the language should look like and there still some open questions there. How can we review an implementation of something where we don't exactly know what we want to build?

**Comment by krishnanm86** [comment]
The basic aspects like having a customizable child/property specification are not going to change and are independent of what the outcome of the open questions are. And this could be later needed for other tasks that come up. 

We can hold the pull request until other aspects of the language are discussed and implemented.

**Comment by eugenschindler** [comment]
@coolya What is the idea of this pull request? It's already open for more than 2 years and should this be integrated?

**Comment by coolya** [comment]
> @coolya What is the idea of this pull request? It's already open for more than 2 years and should this be integrated?

It's been a draft on how the runtime should behave and how a surface DSL for the runtime could look like. There in no implementation to be integrated (yet).

**Comment by alexanderpann** [comment]
Closing because the implementation of the modelmerger is done.

**Pull request closed without merging**
