### PR TITLE
Completing & correcting MPS adapters

### PR DESCRIPTION
**Pull request by ftomassetti**
Correcting errors and completing the information available on dependencies of modules and models. We also consider devkits and the scope of dependencies.
Some tests added.

### CODE REVIEW

**Comment by ftomassetti** [comment]
The PR is intended for MPS 2020.3. If it is accepted I would then move it also to the other branches

**Comment by ftomassetti** [comment]
Please advice if you instead prefer me to work on the newest branches and then backport it

**Comment by slisson** [comment]
Changing older versions first and then merging forward to newer version is preferred, because this forward merging has to be done anyway, even after cherry-picking from a newer to an older version.

**Comment by slisson** [comment]
I merged it into the MPS 2021.1 branch

**Comment by ftomassetti** [comment]
I also see that you later merged the maintenance branch in master, so it seems everything is done. Thank you!
I will wait for the new release of 2020.3

**Pull request merged**
