### PR TITLE
collapsible.runtime: speed-up CollapsibleCell.setCollapsibleCollapsed…

### LINKED ISSUE #312: CollapsibleCell.setCollapsibleCollapsed is slow due to many editor refresh events
I have an editor with a few hundreds of collapsible cells in collapsed mode. I have implemented an action to expand-all of these collapsed cells. The action calls CollapsibleCell.setCollapsibleCollapsed(false) several hundreds of times and is very slow. The problem seems to be that a global editor refresh is done after each call. 

After debugging, it seems that the cause is the many editor-refreshes triggered (screenshot attached). Removing several lines drastically speeds-up the setCollapsibleCollapsed()

image

### PR DESCRIPTION
**Pull request by danielratiu**
… by removing un-needed refresh

fixes #312

### CODE REVIEW

**Comment by slisson** [comment]
Did you check, if editors containing JComponents still behave properly? If not, we can check if there are any EditorCell_WithComponent instances in the descendants before applying this workaround.

**Comment by slisson** [comment]
The failing test already answers the question.

**Comment by danielratiu** [comment]
@slisson thank you for the tips. I will have a look at descendants of my cell to see if there is any EditorCell_WithComponent

**Comment by slisson** [comment]
What I mean is, the .setRootCell call is a workaround required for EditorCell_WithComponent. If there we can put this into an `if` to only execute it when there are any instances of EditorCell_WithComponent.

**Comment by danielratiu** [comment]
I understand - how about the call  to "editorComponent.relayout()" ?

**Comment by slisson** [comment]
That's part of it.

**Comment by danielratiu** [comment]
I have wrapped the expensive code inside a check for descendant cells containing JComponent (EditorCell_WithComponent). Please have a look again ...

**Pull request merged**
