### PR TITLE
Reuse cascading-merge workflow

### PR DESCRIPTION
**Pull request by sergej-koscejev**
Use the reusable cascading merge workflow from specificlanguages/cascading-merge.

### CODE REVIEW

**Comment by sergej-koscejev** [comment]
GitHub says that usage of public reusable workflows needs to be enabled for the organization.

**Comment by alexanderpann** [comment]
> GitHub says that usage of public reusable workflows needs to be enabled for the organization.

We already have the following checkbox enabled: Allow all actions and reusable workflows

**Comment by sergej-koscejev** [comment]
Great, then this should work. I don’t see the current settings, this was just a general advice from the documentation.

**Review by alexanderpann — APPROVED** [review]
LGTM.

**Pull request merged**
