### PR TITLE
Migrate to MPS 2024.1.1

### PR DESCRIPTION
**Pull request by alexanderpann**
- fixes https://github.com/JetBrains/MPS-extensions/issues/918

Nothing special changed. I only had issues with icon loading for plugin models that are nested in other models. Those models couldn't be opened in the logical view. The workaround seems to be to set `Generate initializer config` to true in the `StandalonePluginDescriptor`. The changes related to introducing the XML stubs are related to mbeddr. We need them available in MPS-Extensions since we depend in the batik stubs on then.

Note: We skipped MPS 2023.3 on purpose and decided to immediately go to MPS 2024.1.

Encountered known MPS issues:

- https://youtrack.jetbrains.com/issue/MPS-36888/java.lang.UnsupportedOperationException-not-implemented
- https://youtrack.jetbrains.com/issues/MPS?q=java.lang.IllegalStateException:%20Write%20actions%20are%20prohibited
- https://youtrack.jetbrains.com/issue/MPS-37823/Invalidate-caches-and-restart-Failed-to-close-and-dispose-all-projects
- https://youtrack.jetbrains.com/issue/MPS-37533/idea.log-DisposalException-on-MPS-shutdown 

Other non-migration-related issues:

- https://github.com/JetBrains/MPS-extensions/issues/1003
- https://github.com/JetBrains/MPS-extensions/issues/1004

### CODE REVIEW

**Review by sergej-koscejev — CHANGES_REQUESTED** [review]
* `LineNumberComponent#install`: the editor component disposed check should come even before trying to retrieve the project from the component.
* MyConnectPreview, MyGraphComponent: `getActionUpdateThread()` is only the thread that actions will be _updated_ on, they will still be executed in EDT. Since update is empty, it could be done on BGT because this is preferred.

Requesting changes because XML jars need to be dowloaded with Gradle, not checked into Git.

**Comment by sergej-koscejev** [comment]
Please squash/fixup the commits that add and remove jars, so that we don't have the jars in Git history after merge.

**Comment by sergej-koscejev** [comment]
I am merging the MPS and JBR version update separately in #1010, so that we don't build a 9999.9 version from the 2024.1 branch.

**Comment by alexanderpann** [comment]
Is there anything else that needs to be done, or can this PR be merged now?

**Comment by sergej-koscejev** [comment]
I want to understand why we need those resolver and serializer jars that come from this new Maven repository. Can we get rid of them?

**Comment by alexanderpann** [comment]
I guess you have to check the history in mbeddr why they were introduced: https://github.com/mbeddr/mbeddr.core/tree/master/code/languages/com.mbeddr.mpsutil/solutions/org.xml/lib
As mentioned privately before, the XML serializer is used by IETS3.

**Review by sergej-koscejev — APPROVED** [review]

**Pull request merged**
