### PR TITLE
Enable antialiasing in all math editor cell models

### PR DESCRIPTION
**Pull request by alexanderpann**
Antialiasing was only enabled for math symbols. EditorCellModels such as
math.sqrt didn't use antialising prior to this commit. Fixes IETS3/iets3.opensource#365

### CODE REVIEW

**Comment by dbinkele** [comment]
@alexanderpann @kbirken  There are a lot of places where the core-VoidType still is used. Special Constraints and checking_rules for example. Therefore os-VoidType cannot replace the core-VoidType.  The simple Solution is that core-VoidType extends os-VoidType. Hereby the editor-aspect and the constraint-part of the os-VoidType are inherited. The similar parts of core-VoidType can be deleted. But the additional places where core-VoidType is used MUST be kept. Then also a migration and deprecation is not needed.

**Comment by slisson** [comment]
I would move it to EditorCell_MathBase.paintContent instead of the generator. Then it's part of the runtime and not generated into all subclasses.

**Comment by kbirken** [comment]
> @alexanderpann @kbirken There are a lot of places where the core-VoidType still is used. Special Constraints and checking_rules for example. Therefore os-VoidType cannot replace the core-VoidType. The simple Solution is that core-VoidType extends os-VoidType. Hereby the editor-aspect and the constraint-part of the os-VoidType are inherited. The similar parts of core-VoidType can be deleted. But the additional places where core-VoidType is used MUST be kept. Then also a migration and deprecation is not needed.

@dbinkele This comment is probably at the wrong PR? If yes, pls delete it here to reduce confusion...

**Comment by alexanderpann** [comment]
> I would move it to EditorCell_MathBase.paintContent instead of the generator. Then it's part of the runtime and not generated into all subclasses.

I have moved the changes to EditorCell_MathBase. Let me know if you want any other changes.

**Pull request merged**
