### PR TITLE
Provide new scope class UniqueElementScope

### PR DESCRIPTION
**Pull request by kbirken**
The new scope class `UniqueElementScope` is a delegating scope which ensures that each element is in the scope only once. 

As this is often used in conjunction with a `CompositeScope`, I added a convenience factory method to create an `UniqueElementScope` object from a set of input scopes.

The PR also adds a couple of tests for the new functionality.

This solves issue #969.

### CODE REVIEW

**Comment by kbirken** [comment]
@sergej-koscejev @alexanderpann I don't understand why the build is failing... `Check for dirty files (Command Line) failed`. Is someone trying to imply I'm doing something _dirty_ here? 😇

**Comment by sergej-koscejev** [comment]
> @sergej-koscejev @alexanderpann I don't understand why the build is failing... `Check for dirty files (Command Line) failed`. Is someone trying to imply I'm doing something _dirty_ here? 😇

The build log contains the diff: https://mps.builds.itemis.cloud/buildConfiguration/Mbeddr2_Mbeddr_Gradle_MpsExtensions_PullRequests/368788?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandPull+Request+Details=true&hideProblemsFromDependencies=false&showLog=368788_9908_9892.9893.9953&logView=flowAware

**Comment by kbirken** [comment]
> > @sergej-koscejev @alexanderpann I don't understand why the build is failing... `Check for dirty files (Command Line) failed`. Is someone trying to imply I'm doing something _dirty_ here? 😇
> 
> The build log contains the diff: https://mps.builds.itemis.cloud/buildConfiguration/Mbeddr2_Mbeddr_Gradle_MpsExtensions_PullRequests/368788?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandPull+Request+Details=true&hideProblemsFromDependencies=false&showLog=368788_9908_9892.9893.9953&logView=flowAware

Okay, I saw the diff before, but didn't get what I have to do. Now I ran the migrations, let's see.

**Review by alexanderpann — CHANGES_REQUESTED** [review]
The change looks fine, thanks for the addition. You updated the changelog incorrectly, though. I know it's confusing, we have to find a better way:

Edit the changelog [here](http://127.0.0.1:63320/node?ref=r%3Ac2a03117-d7bb-4287-be70-b5591cc02c98%28de.itemis.mps.extensions.changelog%29%2F4672673781420809189), rebuild the model and execute the task `./gradlew copyChangelog`. Then you can commit your changes.

**Comment by kbirken** [comment]
> The change looks fine, thanks for the addition. You updated the changelog incorrectly, though. I know it's confusing, we have to find a better way:
> 
> Edit the changelog [here](http://127.0.0.1:63320/node?ref=r%3Ac2a03117-d7bb-4287-be70-b5591cc02c98%28de.itemis.mps.extensions.changelog%29%2F4672673781420809189), rebuild the model and execute the task `./gradlew copyChangelog`. Then you can commit your changes.

I reverted the change to `CHANGELOG.md`, and added the item to the changelog root node. But running the gradle-task did not do anything, see screenshot. I pushed my changes, so do you mind to test it on your side?

image

**Comment by kbirken** [comment]
> Seems like you forgot to rebuild the model that contains the changelog before running the Gradle command.

Okay, next try. It would probably help to describe the process in the README and add a little disclaimer to the changelog itself ("Do not edit the CHANGELOG.md directly, cf. ...").

**Review by alexanderpann — APPROVED** [review]
LGTM. It would be nice to have a bot do the step with the gradle task or find a way to not  need this step at all. I don't remember why the Copy-Annotation doesn't work in the generator for this use case.

**Pull request merged**
