### PR TITLE
rerouted all dependencies on guava collections from MPS.IDEA to de.q60.mps.collections.libs

### PR DESCRIPTION
**Pull request by enikao**
rerouted all dependencies on com.google.common.collect(MPS.IDEA/) to com.google.common.collect(de.q60.mps.collections.libs/)

### CODE REVIEW

**Comment by enikao** [comment]
I'd imagine the most critical change is in the Modelix adapter.
@slisson How to test whether that still works?

**Comment by alexanderpann** [comment]
Modelix model-api is deprecated and will be removed in the future as far as I remember, so it is not critical.

**Review by alexanderpann — APPROVED** [review]
LGTM, thanks for the cleanup.

**Comment by enikao** [comment]
@alexanderpann Thanks for merging

**Pull request merged**
