### PR TITLE
Feature/add jackson stubs20201

### PR DESCRIPTION
**Pull request by dbinkele**
Finally works in a RCP as plugin.

### CODE REVIEW

**Comment by slisson** [comment]
Screenshot 2021-05-27 at 10 07 49

This doesn't look right. In the MPS 2020.3 version these jar are not there and they shouldn't.

**Comment by dbinkele** [comment]
> Screenshot 2021-05-27 at 10 07 49
> 
> This doesn't look right. In the MPS 2020.3 version these jar are not there and they shouldn't.

With these me and @wsafonov failed to use the plugin properly. When you use the stubs in some model and you run a build imports are not found..

**Comment by wsafonov** [comment]
> This doesn't look right. In the MPS 2020.3 version these jar are not there and they shouldn't.

Has to be matched to the corresponding MPS version. Looks like Daniel was addressing MPS 2020.1 here, right?

**Comment by slisson** [comment]
What I mean is, that no jars are packaged into the jackson plugin on the branch for MPS 2020.3.

**Comment by wsafonov** [comment]
> What I mean is, that no jars are packaged into the jackson plugin on the branch for MPS 2020.3.

But this is not merged into master, but rather into 2020.1 maintenance. So everything should be ok? Then this needs to be adjusted accordingly for each MPS version .

**Comment by slisson** [comment]
The plugin is supposed to provide stubs for the jars that exist in the MPS libs folder and the class loader should load the classes from the MPS jars. Packaging the jars into the plugin is wrong in all versions.

**Comment by wsafonov** [comment]
Ah, I overlooked that we are packaging here already. True, no jars should be copied from the MPS/lib into a plugin. The idea was to have a plugin with references to the jars in MPS\lib.

**Pull request merged**
