### PR TITLE
Merge maintenance/mps20222 into master

### PR DESCRIPTION
**Pull request by alamqadem**
Update master branch to include latest changes from maintenance/mps20222.

### CODE REVIEW

**Comment by sergej-koscejev** [comment]
Shouldn't this PR use `maintenance/mps20222` as the base branch, so that it gets updated with newer changes? Or do you have some extra changes in the `merge/maintenance-mps20222-into-master` branch?

**Comment by alamqadem** [comment]
> Shouldn't this PR use `maintenance/mps20222` as the source branch, so that it gets updated with newer changes? Or do you have some extra changes in the `merge/maintenance-mps20222-into-master` branch?

No, there are no extra changes.
You're right it should use the `maintenance/mps2022`.
I used this branch because I couldn't enforce the order in which they should be merged.

**Comment by alamqadem** [comment]
Ah no sorry, `master` uses `mps 2022.3`, so that was one of the things that changed in the `build.gradle` from what I recall.

**Comment by alexanderpann** [comment]
The badge in the README is wrong in master, sorry about the confusion.

**Review by alexanderpann — CHANGES_REQUESTED** [review]
Do we still need this branch? Can it be merged?
It yes, please take this as an opportunity to update the badge in the README file to say 2022.3.

**Comment by alexanderpann** [comment]
I already did a cascading merge for all branches. This PR is obsolete.

**Pull request closed without merging**
